/*
 * Copyright 2005 Nick Mathewson, Roger Dingledine
 * See LICENSE file for copying information
 */
package io.anyone.jni;

/**
 * Interface defining constants used by the Anon controller protocol.
 *
 * @see <a href="https://gitweb.torproject.org/torspec.git/tree/control-spec.txt#n257">torspec.git/control-spec.txt 3. Commands</a>
 * @noinspection unused
 */
public interface AnonControlCommands {

    // generated by tools/generate-TorControlCommands.py

    String GENERATED_FROM_TOR_VERSION = "0.4.5.7";

    String SETCONF = "SETCONF";
    String RESETCONF = "RESETCONF";
    String GETCONF = "GETCONF";
    String LOADCONF = "+LOADCONF";
    String SETEVENTS = "SETEVENTS";
    String AUTHENTICATE = "AUTHENTICATE";
    String SAVECONF = "SAVECONF";
    String SIGNAL = "SIGNAL";
    String TAKEOWNERSHIP = "TAKEOWNERSHIP";
    String DROPOWNERSHIP = "DROPOWNERSHIP";
    String MAPADDRESS = "MAPADDRESS";
    String GETINFO = "GETINFO";
    String EXTENDCIRCUIT = "EXTENDCIRCUIT";
    String SETCIRCUITPURPOSE = "SETCIRCUITPURPOSE";
    @Deprecated
    String SETROUTERPURPOSE = "SETROUTERPURPOSE";
    String ATTACHSTREAM = "ATTACHSTREAM";
    String POSTDESCRIPTOR = "+POSTDESCRIPTOR";
    String REDIRECTSTREAM = "REDIRECTSTREAM";
    String CLOSESTREAM = "CLOSESTREAM";
    String CLOSECIRCUIT = "CLOSECIRCUIT";
    String USEFEATURE = "USEFEATURE";
    String RESOLVE = "RESOLVE";
    String PROTOCOLINFO = "PROTOCOLINFO";
    String AUTHCHALLENGE = "AUTHCHALLENGE";
    String DROPGUARDS = "DROPGUARDS";
    String DROPTIMEOUTS = "DROPTIMEOUTS";
    String HSFETCH = "HSFETCH";
    String HSPOST = "+HSPOST";
    String ADD_ONION = "ADD_ONION";
    String DEL_ONION = "DEL_ONION";
    String ONION_CLIENT_AUTH_ADD = "ONION_CLIENT_AUTH_ADD";
    String ONION_CLIENT_AUTH_REMOVE = "ONION_CLIENT_AUTH_REMOVE";
    String ONION_CLIENT_AUTH_VIEW = "ONION_CLIENT_AUTH_VIEW";

    short CMD_ERROR = 0x0000;
    short CMD_DONE = 0x0001;
    short CMD_SETCONF = 0x0002;
    short CMD_RESETCONF = 0x0003;
    short CMD_GETCONF = 0x0004;
    short CMD_LOADCONF = 0x0005;
    short CMD_SETEVENTS = 0x0006;
    short CMD_AUTHENTICATE = 0x0007;
    short CMD_SAVECONF = 0x0008;
    short CMD_SIGNAL = 0x0009;
    short CMD_TAKEOWNERSHIP = 0x000A;
    short CMD_DROPOWNERSHIP = 0x000B;
    short CMD_MAPADDRESS = 0x000C;
    short CMD_GETINFO = 0x000D;
    short CMD_EXTENDCIRCUIT = 0x000E;
    short CMD_SETCIRCUITPURPOSE = 0x000F;
    @Deprecated
    short CMD_SETROUTERPURPOSE = 0x0010;
    short CMD_ATTACHSTREAM = 0x0011;
    short CMD_POSTDESCRIPTOR = 0x0012;
    short CMD_REDIRECTSTREAM = 0x0013;
    short CMD_CLOSESTREAM = 0x0014;
    short CMD_CLOSECIRCUIT = 0x0015;
    short CMD_USEFEATURE = 0x0016;
    short CMD_RESOLVE = 0x0017;
    short CMD_PROTOCOLINFO = 0x0018;
    short CMD_AUTHCHALLENGE = 0x0019;
    short CMD_DROPGUARDS = 0x001A;
    short CMD_DROPTIMEOUTS = 0x001B;
    short CMD_HSFETCH = 0x001C;
    short CMD_HSPOST = 0x001D;
    short CMD_ADD_ONION = 0x001E;
    short CMD_DEL_ONION = 0x001F;
    short CMD_ONION_CLIENT_AUTH_ADD = 0x0020;
    short CMD_ONION_CLIENT_AUTH_REMOVE = 0x0021;
    short CMD_ONION_CLIENT_AUTH_VIEW = 0x0022;

    String[] CMD_NAMES = {
            "ERROR",
            "DONE",
            "SETCONF",
            "RESETCONF",
            "GETCONF",
            "LOADCONF",
            "SETEVENTS",
            "AUTHENTICATE",
            "SAVECONF",
            "SIGNAL",
            "TAKEOWNERSHIP",
            "DROPOWNERSHIP",
            "MAPADDRESS",
            "GETINFO",
            "EXTENDCIRCUIT",
            "SETCIRCUITPURPOSE",
            "SETROUTERPURPOSE",
            "ATTACHSTREAM",
            "POSTDESCRIPTOR",
            "REDIRECTSTREAM",
            "CLOSESTREAM",
            "CLOSECIRCUIT",
            "USEFEATURE",
            "RESOLVE",
            "PROTOCOLINFO",
            "AUTHCHALLENGE",
            "DROPGUARDS",
            "DROPTIMEOUTS",
            "HSFETCH",
            "HSPOST",
            "ADD_ONION",
            "DEL_ONION",
            "ONION_CLIENT_AUTH_ADD",
            "ONION_CLIENT_AUTH_REMOVE",
            "ONION_CLIENT_AUTH_VIEW",
    };

    String CIRCUIT_PURPOSE_C_GENERAL = "general";
    String CIRCUIT_PURPOSE_CONTROLLER = "controller";

    short EVENT_CIRCUIT_STATUS_INDEX = 0x0001;
    short EVENT_CIRCUIT_STATUS_MINOR_INDEX = 0x0002;
    short EVENT_STREAM_STATUS_INDEX = 0x0003;
    short EVENT_OR_CONN_STATUS_INDEX = 0x0004;
    short EVENT_BANDWIDTH_USED_INDEX = 0x0005;
    short EVENT_DEBUG_MSG_INDEX = 0x0006;
    short EVENT_INFO_MSG_INDEX = 0x0007;
    short EVENT_NOTICE_MSG_INDEX = 0x0008;
    short EVENT_WARN_MSG_INDEX = 0x0009;
    short EVENT_ERR_MSG_INDEX = 0x000A;
    short EVENT_NEW_DESC_INDEX = 0x000B;
    short EVENT_ADDRMAP_INDEX = 0x000C;
    short EVENT_DESCCHANGED_INDEX = 0x000D;
    short EVENT_NS_INDEX = 0x000E;
    short EVENT_STATUS_GENERAL_INDEX = 0x000F;
    short EVENT_STATUS_CLIENT_INDEX = 0x0010;
    short EVENT_STATUS_SERVER_INDEX = 0x0011;
    short EVENT_GUARD_INDEX = 0x0012;
    short EVENT_STREAM_BANDWIDTH_USED_INDEX = 0x0013;
    short EVENT_CLIENTS_SEEN_INDEX = 0x0014;
    short EVENT_NEWCONSENSUS_INDEX = 0x0015;
    short EVENT_BUILDTIMEOUT_SET_INDEX = 0x0016;
    short EVENT_GOT_SIGNAL_INDEX = 0x0017;
    short EVENT_CONF_CHANGED_INDEX = 0x0018;
    short EVENT_CONN_BW_INDEX = 0x0019;
    short EVENT_CELL_STATS_INDEX = 0x001A;
    short EVENT_CIRC_BANDWIDTH_USED_INDEX = 0x001B;
    short EVENT_TRANSPORT_LAUNCHED_INDEX = 0x001C;
    short EVENT_HS_DESC_INDEX = 0x001D;
    short EVENT_HS_DESC_CONTENT_INDEX = 0x001E;
    short EVENT_NETWORK_LIVENESS_INDEX = 0x001F;

    String[] EVENT_NAMES = {
            "(0)",
            "CIRC",
            "CIRC_MINOR",
            "STREAM",
            "ORCONN",
            "BW",
            "DEBUG",
            "INFO",
            "NOTICE",
            "WARN",
            "ERR",
            "NEWDESC",
            "ADDRMAP",
            "DESCCHANGED",
            "NS",
            "STATUS_GENERAL",
            "STATUS_CLIENT",
            "STATUS_SERVER",
            "GUARD",
            "STREAM_BW",
            "CLIENTS_SEEN",
//        "NEWCONSENSUS",
            "BUILDTIMEOUT_SET",
            "SIGNAL",
            "CONF_CHANGED",
            "CONN_BW",
            "CELL_STATS",
            "CIRC_BW",
            "TRANSPORT_LAUNCHED",
            "HS_DESC",
//        "HS_DESC_CONTENT",
            "NETWORK_LIVENESS"
    };

    String EVENT_CIRCUIT_STATUS = "CIRC";
    String EVENT_CIRCUIT_STATUS_MINOR = "CIRC_MINOR";
    String EVENT_STREAM_STATUS = "STREAM";
    String EVENT_OR_CONN_STATUS = "ORCONN";
    String EVENT_BANDWIDTH_USED = "BW";
    String EVENT_DEBUG_MSG = "DEBUG";
    String EVENT_INFO_MSG = "INFO";
    String EVENT_NOTICE_MSG = "NOTICE";
    String EVENT_WARN_MSG = "WARN";
    String EVENT_ERR_MSG = "ERR";
    String EVENT_NEW_DESC = "NEWDESC";
    String EVENT_ADDRMAP = "ADDRMAP";
    String EVENT_DESCCHANGED = "DESCCHANGED";
    String EVENT_NS = "NS";
    String EVENT_STATUS_GENERAL = "STATUS_GENERAL";
    String EVENT_STATUS_CLIENT = "STATUS_CLIENT";
    String EVENT_STATUS_SERVER = "STATUS_SERVER";
    String EVENT_GUARD = "GUARD";
    String EVENT_STREAM_BANDWIDTH_USED = "STREAM_BW";
    String EVENT_CLIENTS_SEEN = "CLIENTS_SEEN";
    //    String EVENT_NEWCONSENSUS = "NEWCONSENSUS";
    String EVENT_BUILDTIMEOUT_SET = "BUILDTIMEOUT_SET";
    String EVENT_GOT_SIGNAL = "SIGNAL";
    String EVENT_CONF_CHANGED = "CONF_CHANGED";
    String EVENT_CONN_BW = "CONN_BW";
    String EVENT_CELL_STATS = "CELL_STATS";
    String EVENT_CIRC_BANDWIDTH_USED = "CIRC_BW";
    String EVENT_TRANSPORT_LAUNCHED = "TRANSPORT_LAUNCHED";
    String EVENT_HS_DESC = "HS_DESC";
    //    String EVENT_HS_DESC_CONTENT = "HS_DESC_CONTENT";
    String EVENT_NETWORK_LIVENESS = "NETWORK_LIVENESS";

    byte CIRC_STATUS_LAUNCHED = 0x01;
    byte CIRC_STATUS_BUILT = 0x02;
    byte CIRC_STATUS_EXTENDED = 0x03;
    byte CIRC_STATUS_FAILED = 0x04;
    byte CIRC_STATUS_CLOSED = 0x05;

    String[] CIRC_STATUS_NAMES = {
            "LAUNCHED",
            "BUILT",
            "EXTENDED",
            "FAILED",
            "CLOSED",
    };

    String CIRC_EVENT_LAUNCHED = "LAUNCHED";
    String CIRC_EVENT_BUILT = "BUILT";
    String CIRC_EVENT_EXTENDED = "EXTENDED";
    String CIRC_EVENT_FAILED = "FAILED";
    String CIRC_EVENT_CLOSED = "CLOSED";

    byte STREAM_STATUS_SENT_CONNECT = 0x00;
    byte STREAM_STATUS_SENT_RESOLVE = 0x01;
    byte STREAM_STATUS_SUCCEEDED = 0x02;
    byte STREAM_STATUS_FAILED = 0x03;
    byte STREAM_STATUS_CLOSED = 0x04;
    byte STREAM_STATUS_NEW = 0x05;
    byte STREAM_STATUS_NEW_RESOLVE = 0x06;
    byte STREAM_STATUS_FAILED_RETRIABLE = 0x07;
    byte STREAM_STATUS_REMAP = 0x08;
    byte STREAM_STATUS_CONTROLLER_WAIT = 0x09;

    String[] STREAM_STATUS_NAMES = {
            "SENT_CONNECT",
            "SENT_RESOLVE",
            "SUCCEEDED",
            "FAILED",
            "CLOSED",
            "NEW",
            "NEW_RESOLVE",
            "FAILED_RETRIABLE",
            "REMAP",
            "CONTROLLER_WAIT"
    };

    String STREAM_EVENT_SENT_CONNECT = "SENT_CONNECT";
    String STREAM_EVENT_SENT_RESOLVE = "SENT_RESOLVE";
    String STREAM_EVENT_SUCCEEDED = "SUCCEEDED";
    String STREAM_EVENT_FAILED = "FAILED";
    String STREAM_EVENT_CLOSED = "CLOSED";
    String STREAM_EVENT_NEW = "NEW";
    String STREAM_EVENT_NEW_RESOLVE = "NEW_RESOLVE";
    String STREAM_EVENT_FAILED_RETRIABLE = "FAILED_RETRIABLE";
    String STREAM_EVENT_REMAP = "REMAP";
    String STREAM_EVENT_CONTROLLER_WAIT = "CONTROLLER_WAIT";

    byte OR_CONN_STATUS_LAUNCHED = 0x00;
    byte OR_CONN_STATUS_CONNECTED = 0x01;
    byte OR_CONN_STATUS_FAILED = 0x02;
    byte OR_CONN_STATUS_CLOSED = 0x03;
    byte OR_CONN_STATUS_NEW = 0x04;

    String[] OR_CONN_STATUS_NAMES = {
            "LAUNCHED", "CONNECTED", "FAILED", "CLOSED", "NEW"
    };

    String OR_CONN_EVENT_LAUNCHED = "LAUNCHED";
    String OR_CONN_EVENT_CONNECTED = "CONNECTED";
    String OR_CONN_EVENT_FAILED = "FAILED";
    String OR_CONN_EVENT_CLOSED = "CLOSED";
    String OR_CONN_EVENT_NEW = "NEW";

    /**
     * @see <a href="https://torproject.gitlab.io/torspec/control-spec/#signal">control-spec: SIGNAL</a>
     */
    String SIGNAL_RELOAD = "RELOAD";
    /**
     * @see <a href="https://torproject.gitlab.io/torspec/control-spec/#signal">control-spec: SIGNAL</a>
     */
    String SIGNAL_SHUTDOWN = "SHUTDOWN";
    /**
     * @see <a href="https://torproject.gitlab.io/torspec/control-spec/#signal">control-spec: SIGNAL</a>
     */
    String SIGNAL_DUMP = "DUMP";
    /**
     * @see <a href="https://torproject.gitlab.io/torspec/control-spec/#signal">control-spec: SIGNAL</a>
     */
    String SIGNAL_DEBUG = "DEBUG";
    /**
     * @see <a href="https://torproject.gitlab.io/torspec/control-spec/#signal">control-spec: SIGNAL</a>
     */
    String SIGNAL_HALT = "HALT";
    /**
     * @see <a href="https://torproject.gitlab.io/torspec/control-spec/#signal">control-spec: SIGNAL</a>
     */
    String SIGNAL_NEWNYM = "NEWNYM";
    /**
     * @see <a href="https://torproject.gitlab.io/torspec/control-spec/#signal">control-spec: SIGNAL</a>
     */
    String SIGNAL_CLEARDNSCACHE = "CLEARDNSCACHE";
    /**
     * @see <a href="https://torproject.gitlab.io/torspec/control-spec/#signal">control-spec: SIGNAL</a>
     */
    String SIGNAL_HEARTBEAT = "HEARTBEAT";
    /**
     * @see <a href="https://torproject.gitlab.io/torspec/control-spec/#signal">control-spec: SIGNAL</a>
     */
    String SIGNAL_ACTIVE = "ACTIVE";
    /**
     * @see <a href="https://torproject.gitlab.io/torspec/control-spec/#signal">control-spec: SIGNAL</a>
     */
    String SIGNAL_DORMANT = "DORMANT";

    @Deprecated
    byte SIGNAL_HUP = 0x01;
    @Deprecated
    byte SIGNAL_INT = 0x02;
    @Deprecated
    byte SIGNAL_USR1 = 0x0A;
    @Deprecated
    byte SIGNAL_USR2 = 0x0C;
    @Deprecated
    byte SIGNAL_TERM = 0x0F;

    String[] ERROR_MSGS = {
            "Unspecified error",
            "Internal error",
            "Unrecognized message type",
            "Syntax error",
            "Unrecognized configuration key",
            "Invalid configuration value",
            "Unrecognized byte code",
            "Unauthorized",
            "Failed authentication attempt",
            "Resource exhausted",
            "No such stream",
            "No such circuit",
            "No such OR",
    };

    String HS_ADDRESS = "onionAddress";
    String HS_PRIVKEY = "onionPrivKey";

    @Deprecated
    byte STREAM_STATUS_NEW_CONNECT = STREAM_STATUS_NEW;

    @Deprecated
    short EVENT_CIRCSTATUS = EVENT_CIRCUIT_STATUS_INDEX;
    @Deprecated
    short EVENT_STREAMSTATUS = EVENT_STREAM_STATUS_INDEX;
    @Deprecated
    short EVENT_ORCONNSTATUS = EVENT_OR_CONN_STATUS_INDEX;
    @Deprecated
    short EVENT_BANDWIDTH = EVENT_CONN_BW_INDEX;
    @Deprecated
    short EVENT_MSG_DEBUG = EVENT_DEBUG_MSG_INDEX;
    @Deprecated
    short EVENT_MSG_INFO = EVENT_INFO_MSG_INDEX;
    @Deprecated
    short EVENT_MSG_NOTICE = EVENT_NOTICE_MSG_INDEX;
    @Deprecated
    short EVENT_MSG_WARN = EVENT_WARN_MSG_INDEX;
    @Deprecated
    short EVENT_MSG_ERROR = EVENT_ERR_MSG_INDEX;
}