package io.anyone.jni;

/**
 * Receive the events from Anon.
 * <p>
 * This file is auto-generated by {@code generate-TorControlCommands.py}
 *
 * @see <a href="https://torproject.gitlab.io/torspec/control-spec/#asynchronous-events">Control Port Asynchronous events</a>
 */
public abstract class EventListener implements RawEventListener {

    /**
     * Receive the raw event data from these events:
     * <ul>
     * <li>{@link AnonControlCommands#EVENT_CIRCUIT_STATUS}</li>
     * <li>{@link AnonControlCommands#EVENT_CIRCUIT_STATUS_MINOR}</li>
     * <li>{@link AnonControlCommands#EVENT_STREAM_STATUS}</li>
     * <li>{@link AnonControlCommands#EVENT_OR_CONN_STATUS}</li>
     * <li>{@link AnonControlCommands#EVENT_BANDWIDTH_USED}</li>
     * <li>{@link AnonControlCommands#EVENT_DEBUG_MSG}</li>
     * <li>{@link AnonControlCommands#EVENT_INFO_MSG}</li>
     * <li>{@link AnonControlCommands#EVENT_NOTICE_MSG}</li>
     * <li>{@link AnonControlCommands#EVENT_WARN_MSG}</li>
     * <li>{@link AnonControlCommands#EVENT_ERR_MSG}</li>
     * <li>{@link AnonControlCommands#EVENT_NEW_DESC}</li>
     * <li>{@link AnonControlCommands#EVENT_ADDRMAP}</li>
     * <li>{@link AnonControlCommands#EVENT_DESCCHANGED}</li>
     * <li>{@link AnonControlCommands#EVENT_NS}</li>
     * <li>{@link AnonControlCommands#EVENT_STATUS_GENERAL}</li>
     * <li>{@link AnonControlCommands#EVENT_STATUS_CLIENT}</li>
     * <li>{@link AnonControlCommands#EVENT_STATUS_SERVER}</li>
     * <li>{@link AnonControlCommands#EVENT_GUARD}</li>
     * <li>{@link AnonControlCommands#EVENT_STREAM_BANDWIDTH_USED}</li>
     * <li>{@link AnonControlCommands#EVENT_CLIENTS_SEEN}</li>
     * <li>{@link AnonControlCommands#EVENT_BUILDTIMEOUT_SET}</li>
     * <li>{@link AnonControlCommands#EVENT_GOT_SIGNAL}</li>
     * <li>{@link AnonControlCommands#EVENT_CONF_CHANGED}</li>
     * <li>{@link AnonControlCommands#EVENT_CONN_BW}</li>
     * <li>{@link AnonControlCommands#EVENT_CELL_STATS}</li>
     * <li>{@link AnonControlCommands#EVENT_CIRC_BANDWIDTH_USED}</li>
     * <li>{@link AnonControlCommands#EVENT_TRANSPORT_LAUNCHED}</li>
     * <li>{@link AnonControlCommands#EVENT_HS_DESC}</li>
     * <li>{@link AnonControlCommands#EVENT_NETWORK_LIVENESS}</li>
     * </ul>
     *
     * @see <a href="https://torproject.gitlab.io/torspec/control-spec/#asynchronous-events">Control Port Asynchronous events</a>
     */
    public void onEvent(String keyword, String data) {
        switch(keyword) {
            case AnonControlCommands.EVENT_CIRCUIT_STATUS:
                circuitStatus(data);
                break;
            case AnonControlCommands.EVENT_CIRCUIT_STATUS_MINOR:
                circuitStatusMinor(data);
                break;
            case AnonControlCommands.EVENT_STREAM_STATUS:
                streamStatus(data);
                break;
            case AnonControlCommands.EVENT_OR_CONN_STATUS:
                orConnStatus(data);
                break;
            case AnonControlCommands.EVENT_BANDWIDTH_USED:
                bandwidthUsed(data);
                break;
            case AnonControlCommands.EVENT_DEBUG_MSG:
                debugMsg(data);
                break;
            case AnonControlCommands.EVENT_INFO_MSG:
                infoMsg(data);
                break;
            case AnonControlCommands.EVENT_NOTICE_MSG:
                noticeMsg(data);
                break;
            case AnonControlCommands.EVENT_WARN_MSG:
                warnMsg(data);
                break;
            case AnonControlCommands.EVENT_ERR_MSG:
                errMsg(data);
                break;
            case AnonControlCommands.EVENT_NEW_DESC:
                newDesc(data);
                break;
            case AnonControlCommands.EVENT_ADDRMAP:
                addrMap(data);
                break;
            case AnonControlCommands.EVENT_DESCCHANGED:
                descChanged(data);
                break;
            case AnonControlCommands.EVENT_NS:
                ns(data);
                break;
            case AnonControlCommands.EVENT_STATUS_GENERAL:
                statusGeneral(data);
                break;
            case AnonControlCommands.EVENT_STATUS_CLIENT:
                statusClient(data);
                break;
            case AnonControlCommands.EVENT_STATUS_SERVER:
                statusServer(data);
                break;
            case AnonControlCommands.EVENT_GUARD:
                guard(data);
                break;
            case AnonControlCommands.EVENT_STREAM_BANDWIDTH_USED:
                streamBandwidthUsed(data);
                break;
            case AnonControlCommands.EVENT_CLIENTS_SEEN:
                clientsSeen(data);
                break;
//            case AnonControlCommands.EVENT_NEWCONSENSUS:
//                newConsensus(data);
//                break;
            case AnonControlCommands.EVENT_BUILDTIMEOUT_SET:
                buildTimeoutSet(data);
                break;
            case AnonControlCommands.EVENT_GOT_SIGNAL:
                gotSignal(data);
                break;
            case AnonControlCommands.EVENT_CONF_CHANGED:
                confChanged(data);
                break;
            case AnonControlCommands.EVENT_CONN_BW:
                connBw(data);
                break;
            case AnonControlCommands.EVENT_CELL_STATS:
                cellStats(data);
                break;
            case AnonControlCommands.EVENT_CIRC_BANDWIDTH_USED:
                circBandwidthUsed(data);
                break;
            case AnonControlCommands.EVENT_TRANSPORT_LAUNCHED:
                transportLaunched(data);
                break;
            case AnonControlCommands.EVENT_HS_DESC:
                hsDesc(data);
                break;
//            case AnonControlCommands.EVENT_HS_DESC_CONTENT:
//                hsDescContent(data);
//                break;
            case AnonControlCommands.EVENT_NETWORK_LIVENESS:
                networkLiveness(data);
                break;
            default:
                unrecognized(data);
        }
    }

    public abstract void circuitStatus(String data);

    public abstract void circuitStatusMinor(String data);

    public abstract void streamStatus(String data);

    public abstract void orConnStatus(String data);

    public abstract void bandwidthUsed(String data);

    public abstract void debugMsg(String data);

    public abstract void infoMsg(String data);

    public abstract void noticeMsg(String data);

    public abstract void warnMsg(String data);

    public abstract void errMsg(String data);

    public abstract void newDesc(String data);

    public abstract void addrMap(String data);

    public abstract void descChanged(String data);

    public abstract void ns(String data);

    public abstract void statusGeneral(String data);

    public abstract void statusClient(String data);

    public abstract void statusServer(String data);

    public abstract void guard(String data);

    public abstract void streamBandwidthUsed(String data);

    public abstract void clientsSeen(String data);

//    public abstract void newConsensus(String data);

    public abstract void buildTimeoutSet(String data);

    public abstract void gotSignal(String data);

    public abstract void confChanged(String data);

    public abstract void connBw(String data);

    public abstract void cellStats(String data);

    public abstract void circBandwidthUsed(String data);

    public abstract void transportLaunched(String data);

    public abstract void hsDesc(String data);

//    public abstract void hsDescContent(String data);

    public abstract void networkLiveness(String data);

    public abstract void unrecognized(String data);

}