package io.anyone.jni;

/**
 * Receive the raw event data.
 * <p>
 * This file is auto-generated by {@code generate-TorControlCommands.py}
 *
 * @see <a href="https://torproject.gitlab.io/torspec/control-spec/#asynchronous-events">Control Port Asynchronous events</a>
 */
public interface RawEventListener {

    /**
     * Receive the raw event data from these events:
     * <ul>
     * <li>{@link AnonControlCommands#EVENT_CIRCUIT_STATUS}</li>
     * <li>{@link AnonControlCommands#EVENT_CIRCUIT_STATUS_MINOR}</li>
     * <li>{@link AnonControlCommands#EVENT_STREAM_STATUS}</li>
     * <li>{@link AnonControlCommands#EVENT_OR_CONN_STATUS}</li>
     * <li>{@link AnonControlCommands#EVENT_BANDWIDTH_USED}</li>
     * <li>{@link AnonControlCommands#EVENT_DEBUG_MSG}</li>
     * <li>{@link AnonControlCommands#EVENT_INFO_MSG}</li>
     * <li>{@link AnonControlCommands#EVENT_NOTICE_MSG}</li>
     * <li>{@link AnonControlCommands#EVENT_WARN_MSG}</li>
     * <li>{@link AnonControlCommands#EVENT_ERR_MSG}</li>
     * <li>{@link AnonControlCommands#EVENT_NEW_DESC}</li>
     * <li>{@link AnonControlCommands#EVENT_ADDRMAP}</li>
     * <li>{@link AnonControlCommands#EVENT_DESCCHANGED}</li>
     * <li>{@link AnonControlCommands#EVENT_NS}</li>
     * <li>{@link AnonControlCommands#EVENT_STATUS_GENERAL}</li>
     * <li>{@link AnonControlCommands#EVENT_STATUS_CLIENT}</li>
     * <li>{@link AnonControlCommands#EVENT_STATUS_SERVER}</li>
     * <li>{@link AnonControlCommands#EVENT_GUARD}</li>
     * <li>{@link AnonControlCommands#EVENT_STREAM_BANDWIDTH_USED}</li>
     * <li>{@link AnonControlCommands#EVENT_CLIENTS_SEEN}</li>
     * <li>{@link AnonControlCommands#EVENT_BUILDTIMEOUT_SET}</li>
     * <li>{@link AnonControlCommands#EVENT_GOT_SIGNAL}</li>
     * <li>{@link AnonControlCommands#EVENT_CONF_CHANGED}</li>
     * <li>{@link AnonControlCommands#EVENT_CONN_BW}</li>
     * <li>{@link AnonControlCommands#EVENT_CELL_STATS}</li>
     * <li>{@link AnonControlCommands#EVENT_CIRC_BANDWIDTH_USED}</li>
     * <li>{@link AnonControlCommands#EVENT_TRANSPORT_LAUNCHED}</li>
     * <li>{@link AnonControlCommands#EVENT_HS_DESC}</li>
     * <li>{@link AnonControlCommands#EVENT_NETWORK_LIVENESS}</li>
     * </ul>
     *
     * @see <a href="https://torproject.gitlab.io/torspec/control-spec/#asynchronous-events">Control Port Asynchronous events</a>
     */
    void onEvent(String keyword, String data);
}